### ISSUE TITLE
restore deleted contacts

### ISSUE THREAD

**Issue by jo-thomas-1** [jothomas1996/contacts_book#1]
There must be an option for user to retrieve contacts that were once deleted.

**Comment by augustinpj** [comment]
proposed solution: separate storage for deleted contacts

- When contacts are deleted move them to delete database
- include new function for viewing and restoring the deleted data
- provide option for permanent delete of contact

**Comment by augustinpj** [comment]
deleted contacts are being moved to separate database as per commit f74284d3db0ac334debc0dd4884496bb1a4d1088

**Comment by jo-thomas-1** [comment]
Bug: only single contact is being saved to the deleted database. the next delete is not reflecting in this file even though original data is successfully being deleted. @augustinpj

**Comment by augustinpj** [comment]
bug has been fixed in commit 13122b63edccf0abf13d919246b734dea174e262

**Comment by jo-thomas-1** [comment]
issue cleared :thumbsup:

**Comment by jo-thomas-1** [comment]
update after restore functionality has been completed

**Comment by augustinpj** [comment]
restore functionality added for deleted contacts e611937d879932dd8b49c22570f6368ca4d843ae

**Comment by jo-thomas-1** [comment]
update when other functionalities are completed
